version: "3.3"

services:
  api_server:
    build:
      context: ./api
    ports:
      - '4000:4000'
    restart: always
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.8-alpine
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    restart: always
    environment:
      - INFLUXDB_DB=telconet
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=guillermo
      - INFLUXDB_USER_PASSWORD=guillermo

  chronograf:
    image: chronograf:1.8.4-alpine
    ports:
      - 8888:8888
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin
    volumes:
      - chronograf-storage:/var/lib/chronograf
    restart: always
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:7.1.5
    ports:
      - 3100:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER__FILE=guillermo
      - GF_SECURITY_ADMIN_PASSWORD__FILE=guillermo

volumes:
  influxdb-storage:
  chronograf-storage: